#!/bin/bash

inside_git_repo="$(git rev-parse --is-inside-work-tree 2>/dev/null)"

if [ "$inside_git_repo" ]; then

	git add .
	git commit -m $1
	git push

	echo -e '\n\nDONE!'
else
	echo -e 'Not a git repository'
fi
